name: bluetooth_projesi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.5
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.33.5
  shared_preferences: ^2.3.2
  permission_handler: ^10.0.0
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^27.1.57
  sqflite: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


